apiVersion: v1
kind: Secret
metadata:
  name: mms-user-1-password
  # corresponds to user.spec.passwordSecretKeyRef.name
type: Opaque
stringData:
  password: MyNeatoPassword
  # corresponds to user.spec.passwordSecretKeyRef.key